import React from 'react';
import { 
  Heart, 
  MessageSquare, 
  Clock, 
  Coins, 
  ShieldCheck, 
  Target, 
  Sparkles, 
  AlertTriangle, 
  Share2, 
  Check, 
  UserCheck,
  Flame,
  Bot,
  Timer,
  Hourglass,
  Zap,
  CheckCircle2,
  TrendingUp
} from 'lucide-react';
import { DareItem, UserProfile, DareStatus } from '../types';
import { playSound } from '../utils/soundEffects';
import { copyToClipboard, getDareShareUrl } from '../utils/clipboard';

interface DareCardProps {
  dare: DareItem;
  currentUser: UserProfile;
  onAccept: (dare: DareItem) => void;
  onSubmitProof: (dare: DareItem) => void;
  onViewProof: (dare: DareItem) => void;
  onToggleLike: (dareId: string) => void;
  onToggleComments: (dare: DareItem) => void;
  onShare?: (dare: DareItem, url: string) => void;
  onOpenProfile?: (userId: string) => void;
  onOpenCoach?: (dare: DareItem) => void;
  onOpenStake?: (dare: DareItem) => void;
  onOpenShareCard?: (dare: DareItem) => void;
  isHighlighted?: boolean;
}

export const DareCard: React.FC<DareCardProps> = ({
  dare,
  currentUser,
  onAccept,
  onSubmitProof,
  onViewProof,
  onToggleLike,
  onToggleComments,
  onShare,
  onOpenProfile,
  onOpenCoach,
  onOpenStake,
  onOpenShareCard,
  isHighlighted = false,
}) => {
  const [copied, setCopied] = React.useState(false);
  const isLiked = dare.likedUserIds.includes(currentUser.id);
  const isAcceptedByMe = dare.acceptedBy?.handle === currentUser.handle;
  const isTargetedToMe = dare.targetType === 'direct' && dare.targetUserHandle === currentUser.handle;

  // Active challenge status (either open bounty on the grid or accepted challenge underway)
  const isActiveChallenge = dare.status === 'open' || dare.status === 'accepted';

  // Calculate target expiry time with robust fallbacks
  const targetExpiryTime = React.useMemo(() => {
    if (!isActiveChallenge) return null;
    
    if (dare.expiresAt) {
      const parsed = new Date(dare.expiresAt).getTime();
      if (!isNaN(parsed)) return parsed;
    }
    
    // Fallback based on challenge lifecycle:
    // If accepted underway: 36h execution window from acceptance or creation
    if (dare.status === 'accepted') {
      const base = dare.acceptedAt ? new Date(dare.acceptedAt).getTime() : new Date(dare.createdAt).getTime();
      return base + 36 * 3600 * 1000;
    }
    
    // If open bounty: 48h window from creation
    if (dare.status === 'open') {
      const base = new Date(dare.createdAt).getTime();
      return base + 48 * 3600 * 1000;
    }
    
    return null;
  }, [dare.expiresAt, dare.status, dare.acceptedAt, dare.createdAt, isActiveChallenge]);

  // Live countdown state ticking every second
  const [remainingMs, setRemainingMs] = React.useState<number | null>(() => {
    if (!targetExpiryTime) return null;
    return Math.max(0, targetExpiryTime - Date.now());
  });

  React.useEffect(() => {
    if (!targetExpiryTime) {
      setRemainingMs(null);
      return;
    }

    const updateTimer = () => {
      const diff = Math.max(0, targetExpiryTime - Date.now());
      setRemainingMs(diff);
    };

    updateTimer();
    const interval = setInterval(updateTimer, 1000);
    return () => clearInterval(interval);
  }, [targetExpiryTime]);

  // Derive time components
  const totalSeconds = remainingMs !== null ? Math.floor(remainingMs / 1000) : 0;
  const isExpired = remainingMs !== null && remainingMs <= 0;
  const days = Math.floor(totalSeconds / 86400);
  const hours = Math.floor((totalSeconds % 86400) / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);
  const seconds = totalSeconds % 60;

  // Determine urgency tier for active challenges
  const urgencyTier: 'critical' | 'high' | 'standard' | 'expired' = React.useMemo(() => {
    if (!isActiveChallenge) return 'standard';
    if (isExpired) return 'expired';
    if (remainingMs !== null && remainingMs < 2 * 3600 * 1000) return 'critical'; // < 2h
    if (remainingMs !== null && remainingMs < 12 * 3600 * 1000) return 'high'; // < 12h
    return 'standard';
  }, [isActiveChallenge, isExpired, remainingMs]);

  // Compact string for buttons/badges
  const compactTimeLeft = isExpired 
    ? 'Expired' 
    : `${days > 0 ? `${days}d ` : ''}${String(hours).padStart(2, '0')}h ${String(minutes).padStart(2, '0')}m ${String(seconds).padStart(2, '0')}s`;

  // Dynamic Trending activity calculation (> 10 comments or likes in the last 24 hours)
  const trendingData = React.useMemo(() => {
    const now = Date.now();
    const ONE_DAY_MS = 24 * 3600 * 1000;

    // 1. Calculate comments within the last 24 hours
    const recentComments = (dare.comments || []).filter((c) => {
      if (!c.timestamp) return false;
      const lower = c.timestamp.toLowerCase();
      // Relative timestamps commonly generated by users / seeds: 'X mins ago', 'X hours ago', 'just now', 'today'
      if (
        lower.includes('min') ||
        lower.includes('hour') ||
        lower.includes('sec') ||
        lower.includes('just now') ||
        lower.includes('today')
      ) {
        return true;
      }
      const parsed = new Date(c.timestamp).getTime();
      if (!isNaN(parsed)) {
        return now - parsed <= ONE_DAY_MS;
      }
      return false;
    }).length;

    // 2. Calculate likes within the last 24 hours
    // If the dare was created within the last 24 hours, all its recorded likes occurred in the last 24 hours
    const createdTime = dare.createdAt ? new Date(dare.createdAt).getTime() : now;
    const dareAgeMs = Math.max(0, now - createdTime);
    let recentLikes = dare.likes || 0;

    if (dareAgeMs > ONE_DAY_MS) {
      // For older challenges, normalize daily engagement volume
      const days = Math.max(1, dareAgeMs / ONE_DAY_MS);
      recentLikes = Math.round((dare.likes || 0) / days);
    }

    const totalRecentActivity = recentComments + recentLikes;
    // Criteria: high activity levels (> 10 comments or likes in the last 24 hours)
    const isTrending = recentComments > 10 || recentLikes > 10 || totalRecentActivity > 10;

    return {
      isTrending,
      recentComments,
      recentLikes,
      totalRecentActivity,
    };
  }, [dare.comments, dare.likes, dare.createdAt]);

  // Dynamic Difficulty Level based on rewardCred bounty amount
  const getDifficultyFromReward = (cred: number) => {
    if (cred < 45) {
      return {
        label: 'Easy',
        sublabel: 'Tier 1 // Low Risk',
        border: 'border-emerald-500/50',
        text: 'text-emerald-300',
        bg: 'bg-emerald-950/40',
        glow: 'glow-green',
        dot: 'bg-emerald-400',
        badgeClass: 'border-emerald-500/50 bg-emerald-950/50 text-emerald-300 shadow-[0_0_12px_rgba(16,185,129,0.25)]',
      };
    }
    if (cred < 80) {
      return {
        label: 'Medium',
        sublabel: 'Tier 2 // Standard',
        border: 'border-cyan-500/50',
        text: 'text-cyan-300',
        bg: 'bg-cyan-950/40',
        glow: 'glow-cyan',
        dot: 'bg-cyan-400',
        badgeClass: 'border-cyan-500/50 bg-cyan-950/50 text-cyan-300 shadow-[0_0_12px_rgba(6,182,212,0.25)]',
      };
    }
    if (cred < 140) {
      return {
        label: 'Hard',
        sublabel: 'Tier 3 // High Voltage',
        border: 'border-amber-500/60',
        text: 'text-amber-300',
        bg: 'bg-amber-950/40',
        glow: 'glow-amber',
        dot: 'bg-amber-400',
        badgeClass: 'border-amber-500/60 bg-amber-950/50 text-amber-300 shadow-[0_0_14px_rgba(245,158,11,0.28)]',
      };
    }
    return {
      label: 'Extreme',
      sublabel: 'Tier 4 // Cyber Psycho',
      border: 'border-rose-500/70',
      text: 'text-rose-300',
      bg: 'bg-rose-950/50',
      glow: 'glow-magenta',
      dot: 'bg-rose-400 animate-pulse',
      badgeClass: 'border-rose-500/70 bg-rose-950/60 text-rose-300 shadow-[0_0_18px_rgba(244,63,94,0.35)] animate-pulse',
    };
  };

  const diffStyle = getDifficultyFromReward(dare.rewardCred);

  // Dynamic distinct, color-coded status badge configuration
  const getStatusBadgeConfig = (status: DareStatus, acceptedByHandle?: string) => {
    switch (status) {
      case 'accepted':
        return {
          id: 'in-progress',
          label: 'In Progress',
          tooltip: acceptedByHandle ? `Active challenge underway by ${acceptedByHandle}` : 'Active challenge underway',
          badgeClass: 'border-amber-500/70 bg-amber-950/80 text-amber-300 shadow-[0_0_14px_rgba(245,158,11,0.3)] glow-amber',
          dotClass: 'bg-amber-400',
          ping: true,
          icon: <Clock className="h-3 w-3 text-amber-400" />,
        };
      case 'submitted':
        return {
          id: 'awaiting-verdict',
          label: 'Awaiting Verdict',
          tooltip: 'Proof submitted — AI Oracle and community review in progress',
          badgeClass: 'border-purple-500/70 bg-purple-950/80 text-purple-300 shadow-[0_0_14px_rgba(168,85,247,0.3)] glow-purple',
          dotClass: 'bg-purple-400',
          ping: true,
          icon: <Hourglass className="h-3 w-3 text-purple-400 animate-spin" />,
        };
      case 'verified':
        return {
          id: 'completed',
          label: 'Completed',
          tooltip: 'Verified Legit — Challenge completed and bounty awarded',
          badgeClass: 'border-emerald-500/70 bg-emerald-950/80 text-emerald-300 shadow-[0_0_14px_rgba(16,185,129,0.3)] glow-green',
          dotClass: 'bg-emerald-400',
          ping: false,
          icon: <CheckCircle2 className="h-3 w-3 text-emerald-400" />,
        };
      case 'rejected':
        return {
          id: 'busted',
          label: 'Busted',
          tooltip: 'Proof deemed illegitimate by community or AI arbiter',
          badgeClass: 'border-rose-500/70 bg-rose-950/80 text-rose-300 shadow-[0_0_12px_rgba(244,63,94,0.3)] glow-magenta',
          dotClass: 'bg-rose-400',
          ping: false,
          icon: <AlertTriangle className="h-3 w-3 text-rose-400" />,
        };
      case 'forfeited':
        return {
          id: 'forfeited',
          label: 'Forfeited',
          tooltip: 'Challenge lapsed or forfeited',
          badgeClass: 'border-slate-700 bg-slate-900/90 text-slate-400',
          dotClass: 'bg-slate-500',
          ping: false,
          icon: <AlertTriangle className="h-3 w-3 text-slate-400" />,
        };
      case 'open':
      default:
        return {
          id: 'open',
          label: 'Open Bounty',
          tooltip: 'Open bounty available for any challenger to claim',
          badgeClass: 'border-cyan-500/70 bg-cyan-950/80 text-cyan-300 shadow-[0_0_14px_rgba(6,182,212,0.3)] glow-cyan',
          dotClass: 'bg-cyan-400',
          ping: true,
          icon: <Zap className="h-3 w-3 text-cyan-400" />,
        };
    }
  };

  const statusConfig = getStatusBadgeConfig(dare.status, dare.acceptedBy?.handle);

  const handleCopyLink = async () => {
    playSound('click');
    const shareUrl = getDareShareUrl(dare.id);
    await copyToClipboard(shareUrl);
    setCopied(true);
    if (onShare) {
      onShare(dare, shareUrl);
    }
    setTimeout(() => setCopied(false), 2600);
  };

  const handleNativeShare = async () => {
    if (onOpenShareCard) {
      playSound('click');
      onOpenShareCard(dare);
      return;
    }
    playSound('click');
    const shareUrl = getDareShareUrl(dare.id);
    try {
      if (navigator.share) {
        await navigator.share({
          title: `DARE Challenge: ${dare.title}`,
          text: dare.description,
          url: shareUrl,
        });
      } else {
        handleCopyLink();
      }
    } catch (err) {
      if ((err as Error).name !== 'AbortError') {
        console.error('Error sharing:', err);
        handleCopyLink();
      }
    }
  };

  // Border and glow adjustments based on status, urgency, highlighted state, and reward difficulty tier
  const getCardBorderClasses = () => {
    if (isHighlighted) {
      return 'border-indigo-500 ring-2 ring-indigo-500/20 shadow-lg';
    }
    if (dare.isHolographic || dare.creator?.isPro) {
      return 'border-pink-500/50 shadow-md';
    }
    if (dare.status === 'verified') {
      return 'border-emerald-500/30 hover:border-emerald-500/50 hover:shadow-md';
    }
    if (dare.status === 'submitted') {
      return 'border-purple-500/30 hover:border-purple-500/50 hover:shadow-md';
    }
    if (dare.status === 'accepted') {
      if (urgencyTier === 'critical') {
        return 'border-rose-500/50 hover:border-rose-500/70 hover:shadow-md';
      }
      if (urgencyTier === 'high') {
        return 'border-amber-500/40 hover:border-amber-500/60 hover:shadow-md';
      }
      return 'border-amber-500/30 hover:border-amber-500/50 hover:shadow-md';
    }
    if (isTargetedToMe) {
      return 'border-pink-500/40 hover:border-pink-500/60 hover:shadow-md';
    }
    // Standard tiers
    if (dare.rewardCred >= 140) {
      return 'border-slate-800 hover:border-rose-500/40 hover:shadow-md';
    }
    if (dare.rewardCred >= 80) {
      return 'border-slate-800 hover:border-amber-500/40 hover:shadow-md';
    }
    if (dare.rewardCred >= 45) {
      return 'border-slate-800 hover:border-indigo-500/40 hover:shadow-md';
    }
    return 'border-slate-800 hover:border-emerald-500/40 hover:shadow-md';
  };

  // Dynamic subtle background glow gradient based on reward tier or status
  const getCardGlowGradient = () => {
    if (dare.status === 'verified') {
      return 'from-emerald-500/10 via-emerald-950/20 to-transparent';
    }
    if (dare.status === 'submitted') {
      return 'from-purple-500/12 via-purple-950/20 to-transparent';
    }
    if (dare.status === 'accepted') {
      return 'from-amber-500/12 via-amber-950/20 to-transparent';
    }
    if (trendingData.isTrending && dare.status === 'open') {
      return 'from-orange-500/15 via-amber-950/20 to-transparent';
    }
    if (isTargetedToMe || (isActiveChallenge && urgencyTier === 'critical') || dare.rewardCred >= 140) {
      return 'from-rose-500/12 via-pink-950/20 to-transparent';
    }
    if (dare.rewardCred >= 80) {
      return 'from-amber-500/10 via-amber-950/20 to-transparent';
    }
    if (dare.rewardCred >= 45) {
      return 'from-indigo-500/10 via-slate-900/10 to-transparent';
    }
    return 'from-emerald-500/8 via-emerald-950/15 to-transparent';
  };

  return (
    <div 
      id={`dare-card-${dare.id}`}
      className={`group relative flex flex-col justify-between rounded-2xl border bg-[#0b0f19]/90 backdrop-blur-md p-4 sm:p-5 transition-all duration-300 ease-out hover:-translate-y-1 hover:bg-[#0d1322] overflow-hidden ${getCardBorderClasses()}`}
    >
      {/* Background Interactive Ambient Glow Shift on Hover */}
      <div 
        aria-hidden="true"
        className={`pointer-events-none absolute -inset-px rounded-2xl bg-gradient-to-br ${getCardGlowGradient()} opacity-0 transition-opacity duration-500 ease-out group-hover:opacity-100`} 
      />

      {/* Cyber Grid Accent Shimmer on Card Top Corner */}
      <div 
        aria-hidden="true"
        className="pointer-events-none absolute top-0 right-0 h-28 w-28 rounded-tr-2xl bg-gradient-to-bl from-white/[0.04] to-transparent opacity-0 transition-opacity duration-300 group-hover:opacity-100"
      />

      {/* Main Card Content Container */}
      <div className="relative z-10 flex flex-col justify-between h-full min-w-0">
        <div>
          {/* Top Header: Distinct Status Badge, Target Type, Difficulty & Reward Bounty */}
          <div className="flex flex-wrap items-center justify-between gap-2 mb-3 min-w-0">
            {/* Status Badge, Target Badge & Difficulty */}
            <div className="flex flex-wrap items-center gap-1.5 min-w-0 flex-1">
              {isHighlighted && (
                <span className="inline-flex items-center gap-1 rounded-md border border-indigo-500/30 bg-indigo-950/60 px-2 py-0.5 text-[10px] font-sans font-semibold tracking-wide text-indigo-300 shrink-0">
                  <Sparkles className="h-3 w-3 text-indigo-400" />
                  Target
                </span>
              )}

              {/* Distinct Color-Coded Status Badge */}
              <span 
                id={`dare-status-badge-${dare.id}`}
                title={statusConfig.tooltip}
                className={`inline-flex items-center gap-1.5 rounded-md border px-2 py-0.5 text-[10px] font-mono font-bold tracking-wider uppercase transition-all select-none shrink-0 ${statusConfig.badgeClass}`}
              >
                <span className="relative flex h-2 w-2 items-center justify-center">
                  {statusConfig.ping && (
                    <span className={`animate-ping absolute inline-flex h-full w-full rounded-full opacity-75 ${statusConfig.dotClass}`} />
                  )}
                  <span className={`relative inline-flex rounded-full h-1.5 w-1.5 ${statusConfig.dotClass}`} />
                </span>
                {statusConfig.icon}
                <span>{statusConfig.label}</span>
              </span>

              {/* Dynamic Trending Badge for High Activity Levels (> 10 comments or likes in the last 24h) */}
              {trendingData.isTrending && (
                <span 
                  id={`trending-badge-${dare.id}`}
                  title={`Trending Challenge: High engagement with ${trendingData.totalRecentActivity} interactions (${trendingData.recentLikes} likes, ${trendingData.recentComments} comments) in the last 24 hours`}
                  className="inline-flex items-center gap-1 rounded-md border border-orange-500/60 bg-gradient-to-r from-amber-950/70 via-orange-950/60 to-rose-950/70 px-2 py-0.5 text-[10px] font-mono font-bold tracking-wider uppercase text-orange-300 shadow-[0_0_12px_rgba(249,115,22,0.25)] shrink-0 transition-transform hover:scale-105 select-none"
                >
                  <Flame className="h-3 w-3 text-orange-400 fill-orange-400/40 shrink-0 animate-pulse" />
                  <span>Trending</span>
                </span>
              )}

              {/* Target Type Badge */}
              {dare.targetType === 'public' ? (
                <span className="inline-flex items-center gap-1 rounded-md border border-slate-800 bg-slate-900/60 px-2 py-0.5 text-[10px] font-mono font-semibold uppercase tracking-wider text-slate-400 shrink-0">
                  <Target className="h-3 w-3 text-indigo-400/80" />
                  Public
                </span>
              ) : (
                <button
                  id={`card-target-user-${dare.id}`}
                  onClick={(e) => {
                    e.stopPropagation();
                    playSound('click');
                    if (dare.targetUserHandle) {
                      onOpenProfile?.(dare.targetUserHandle);
                    }
                  }}
                  className="inline-flex items-center gap-1 rounded-md border border-pink-500/30 bg-pink-950/30 px-2 py-0.5 text-[10px] font-mono font-bold uppercase tracking-wider text-pink-300 shrink-0 max-w-[130px] truncate hover:border-pink-400 hover:bg-pink-900/40 transition-colors cursor-pointer active:scale-95"
                  title={`View ${dare.targetUserHandle}'s Profile`}
                >
                  <Flame className="h-3 w-3 text-pink-400 shrink-0" />
                  <span className="truncate">For {dare.targetUserHandle || 'Peer'}</span>
                </button>
              )}

              {/* Dynamic Difficulty Level Badge based on Reward Amount */}
              <span 
                id={`difficulty-badge-${dare.id}`}
                title={`${diffStyle.label} Difficulty (${dare.rewardCred} Cred Reward)`}
                className={`inline-flex items-center gap-1 rounded-md border px-2 py-0.5 text-[10px] font-mono font-bold tracking-wider uppercase transition-all shrink-0 ${diffStyle.badgeClass}`}
              >
                <span className={`h-1.5 w-1.5 rounded-full ${diffStyle.dot}`} />
                <span>{diffStyle.label}</span>
              </span>
            </div>

            {/* Bounty Reward */}
            <div className="flex items-center gap-1.5 rounded-full border border-amber-500/40 bg-amber-950/40 px-2.5 py-0.5 text-xs font-mono font-bold text-amber-300 shadow-sm shrink-0">
              <Coins className="h-3.5 w-3.5 text-amber-400" />
              <span>+{dare.rewardCred}</span>
            </div>
          </div>

          {/* Time-To-Expiry Countdown Telemetry Strip for Active Challenges */}
          {isActiveChallenge && (
            <div 
              id={`countdown-strip-${dare.id}`}
              className={`mb-3 rounded-xl border p-2 transition-all flex flex-col gap-1.5 text-xs font-mono min-w-0 ${
                urgencyTier === 'expired'
                  ? 'border-rose-600/70 bg-rose-950/30 text-rose-300'
                  : urgencyTier === 'critical'
                  ? 'border-rose-500/70 bg-rose-950/40 text-rose-200 shadow-[0_0_15px_rgba(244,63,94,0.2)] animate-pulse'
                  : urgencyTier === 'high'
                  ? 'border-amber-500/50 bg-amber-950/30 text-amber-200 shadow-[0_0_12px_rgba(245,158,11,0.15)]'
                  : 'border-cyan-500/30 bg-cyan-950/20 text-cyan-200'
              }`}
            >
              <div className="flex items-center justify-between gap-2">
                {/* Left label & urgency badge */}
                <div className="flex items-center gap-1.5 min-w-0 truncate">
                  {urgencyTier === 'expired' ? (
                    <AlertTriangle className="h-3.5 w-3.5 text-rose-400 shrink-0" />
                  ) : urgencyTier === 'critical' ? (
                    <Flame className="h-3.5 w-3.5 text-rose-400 shrink-0 animate-bounce" />
                  ) : urgencyTier === 'high' ? (
                    <Clock className="h-3.5 w-3.5 text-amber-400 shrink-0" />
                  ) : (
                    <Timer className="h-3.5 w-3.5 text-cyan-400 shrink-0" />
                  )}

                  <span className="font-bold text-[10px] uppercase tracking-wider truncate">
                    {dare.status === 'accepted' ? 'Execution Window' : 'Bounty Clock'}
                  </span>

                  {urgencyTier === 'critical' && (
                    <span className="rounded bg-rose-500/40 px-1 py-0.2 text-[9px] font-black text-rose-200 border border-rose-400/50 shrink-0">
                      &lt; 2H
                    </span>
                  )}
                  {urgencyTier === 'high' && (
                    <span className="rounded bg-amber-500/30 px-1 py-0.2 text-[9px] font-bold text-amber-300 border border-amber-400/40 shrink-0">
                      FAST
                    </span>
                  )}
                </div>

                {/* Right: Clean Digital Segmented Clock Readout */}
                <div className="shrink-0 flex items-center">
                  {isExpired ? (
                    <span className="rounded border border-rose-500/60 bg-rose-950/80 px-2 py-0.5 text-[10px] font-bold text-rose-300 font-mono tracking-wider">
                      EXPIRED
                    </span>
                  ) : (
                    <div className="flex items-center gap-0.5 font-mono text-[11px] font-bold select-none text-cyan-300 bg-black/40 px-1.5 py-0.5 rounded border border-white/5">
                      {days > 0 && <span>{days}d </span>}
                      <span>{String(hours).padStart(2, '0')}:</span>
                      <span>{String(minutes).padStart(2, '0')}:</span>
                      <span className={urgencyTier === 'critical' ? 'text-rose-400' : 'text-cyan-400'}>
                        {String(seconds).padStart(2, '0')}
                      </span>
                    </div>
                  )}
                </div>
              </div>

              {/* Scrolling Telemetry Live Text */}
              <div className="w-full overflow-hidden border-t border-white/5 pt-1 ticker-mask">
                <div className="animate-ticker inline-flex items-center gap-6 text-[10px] text-slate-300 font-mono select-none">
                  <span className="flex items-center gap-1.5">
                    <span className="h-1.5 w-1.5 rounded-full bg-cyan-400 animate-pulse" />
                    {dare.status === 'accepted'
                      ? isAcceptedByMe
                        ? 'ACTION REQUIRED // Submit video or photo proof before deadline expires'
                        : `CHALLENGER ON CLOCK // @${dare.acceptedBy?.handle || 'Peer'} is currently executing challenge`
                      : `ACTIVE BOUNTY // Claim and complete challenge to win +${dare.rewardCred} Cred`}
                  </span>
                  <span className="text-slate-600 font-bold">•</span>
                  <span className="flex items-center gap-1 text-amber-300">
                    <Coins className="h-3 w-3 text-amber-400" />
                    +{dare.rewardCred} Cred Reward
                  </span>
                  <span className="text-slate-600 font-bold">•</span>
                  <span className="text-cyan-300">
                    AI Arbiter Consensus Protocol
                  </span>
                  <span className="text-slate-600 font-bold">•</span>

                  {/* Duplicate segment for seamless infinite scroll */}
                  <span className="flex items-center gap-1.5">
                    <span className="h-1.5 w-1.5 rounded-full bg-cyan-400 animate-pulse" />
                    {dare.status === 'accepted'
                      ? isAcceptedByMe
                        ? 'ACTION REQUIRED // Submit video or photo proof before deadline expires'
                        : `CHALLENGER ON CLOCK // @${dare.acceptedBy?.handle || 'Peer'} is currently executing challenge`
                      : `ACTIVE BOUNTY // Claim and complete challenge to win +${dare.rewardCred} Cred`}
                  </span>
                  <span className="text-slate-600 font-bold">•</span>
                  <span className="flex items-center gap-1 text-amber-300">
                    <Coins className="h-3 w-3 text-amber-400" />
                    +{dare.rewardCred} Cred Reward
                  </span>
                  <span className="text-slate-600 font-bold">•</span>
                  <span className="text-cyan-300">
                    AI Arbiter Consensus Protocol
                  </span>
                  <span className="text-slate-600 font-bold">•</span>
                </div>
              </div>
            </div>
          )}

          {/* Open Dares Scrolling Telemetry Banner */}
          {dare.status === 'open' && (
            <div className="mb-2.5 rounded-lg border border-cyan-500/20 bg-cyan-950/20 px-2 py-1 overflow-hidden ticker-mask">
              <div className="animate-ticker inline-flex items-center gap-6 text-[10px] text-cyan-300/90 font-mono select-none">
                <span className="flex items-center gap-1">
                  <Sparkles className="h-3 w-3 text-cyan-400" />
                  OPEN CHALLENGE • Earn +{dare.rewardCred} Cred • Click 'Accept Challenge' to begin
                </span>
                <span className="text-cyan-600">•</span>
                <span>Instant Acceptance • Community Verification • AI Safe</span>
                <span className="text-cyan-600">•</span>
                <span className="flex items-center gap-1">
                  <Sparkles className="h-3 w-3 text-cyan-400" />
                  OPEN CHALLENGE • Earn +{dare.rewardCred} Cred • Click 'Accept Challenge' to begin
                </span>
                <span className="text-cyan-600">•</span>
                <span>Instant Acceptance • Community Verification • AI Safe</span>
                <span className="text-cyan-600">•</span>
              </div>
            </div>
          )}

          {/* Dare Title */}
          <h3 className="font-tech text-base sm:text-lg font-bold text-white leading-snug group-hover:text-cyan-300 transition-colors break-words line-clamp-2">
            {dare.title}
          </h3>

          {/* Description */}
          <p className="mt-1.5 text-xs text-slate-300 leading-relaxed line-clamp-3 break-words">
            {dare.description}
          </p>

          {/* Proof Requirement Callout */}
          <div className="mt-3 rounded-xl border border-slate-800/80 bg-[#07090e]/80 p-2.5 text-[11px]">
            <div className="flex items-center gap-1 text-slate-400 font-mono font-semibold uppercase tracking-wider text-[10px]">
              <ShieldCheck className="h-3 w-3 text-cyan-400 shrink-0" />
              <span>Proof Requirement:</span>
            </div>
            <p className="mt-1 text-slate-300 font-mono text-[11px] leading-relaxed break-words line-clamp-2">
              {dare.proofRequirement}
            </p>
          </div>

          {/* AI Dare Coach Interactive Trigger */}
          <div className="mt-2.5">
            <button
              id={`ai-coach-banner-btn-${dare.id}`}
              type="button"
              onClick={(e) => {
                e.stopPropagation();
                playSound('laser');
                onOpenCoach?.(dare);
              }}
              className="w-full flex items-center justify-between gap-2 px-3 py-1.5 rounded-xl border border-indigo-500/30 bg-gradient-to-r from-indigo-950/40 via-purple-950/20 to-slate-900/60 hover:border-indigo-400 hover:from-indigo-950/70 hover:to-purple-900/40 text-indigo-300 hover:text-white transition-all text-xs font-mono font-bold cursor-pointer"
            >
              <div className="flex items-center gap-1.5 min-w-0 truncate">
                <Bot className="h-3.5 w-3.5 text-indigo-400 shrink-0" />
                <span className="truncate">AI Oracle</span>
              </div>
              <span className="text-[10px] text-indigo-400 font-normal shrink-0">
                Briefing →
              </span>
            </button>
          </div>

          {/* Proof / Verification Status Banner if present */}
          {dare.proof && (
            <div className={`mt-2.5 rounded-xl border p-2 text-xs min-w-0 ${
              dare.status === 'verified'
                ? 'border-emerald-500/40 bg-emerald-950/30 text-emerald-200'
                : 'border-purple-500/40 bg-purple-950/30 text-purple-200 shadow-[0_0_12px_rgba(168,85,247,0.15)]'
            }`}>
              <div className="flex items-center justify-between gap-2">
                <div className="flex items-center gap-1 font-mono text-[10px] font-bold min-w-0 truncate">
                  {dare.status === 'verified' ? (
                    <>
                      <CheckCircle2 className="h-3 w-3 text-emerald-400 shrink-0" />
                      <span className="truncate">VERIFIED LEGIT</span>
                    </>
                  ) : (
                    <>
                      <Hourglass className="h-3 w-3 text-purple-400 animate-spin shrink-0" />
                      <span className="truncate">AWAITING VERDICT</span>
                    </>
                  )}
                </div>
                <button
                  id={`view-proof-btn-${dare.id}`}
                  onClick={() => {
                    playSound('click');
                    onViewProof(dare);
                  }}
                  className={`text-[10px] font-mono font-semibold underline shrink-0 transition-colors ${
                    dare.status === 'verified' ? 'text-emerald-400 hover:text-emerald-300' : 'text-purple-400 hover:text-purple-300'
                  }`}
                >
                  Inspect Proof →
                </button>
              </div>
            </div>
          )}
        </div>

        {/* Footer Info & Actions */}
        <div className="mt-4 border-t border-slate-800/60 pt-3">
          {/* Creator & Challenger Row */}
          <div className="flex items-center justify-between text-xs text-slate-400 mb-2.5 gap-2 min-w-0">
            <button
              id={`card-creator-profile-${dare.id}`}
              onClick={(e) => {
                e.stopPropagation();
                playSound('click');
                onOpenProfile?.(dare.creator.id || dare.creator.handle);
              }}
              className="flex items-center gap-1.5 hover:opacity-100 transition-all cursor-pointer group/creator text-left min-w-0 truncate py-1 px-1.5 -ml-1 rounded-lg hover:bg-slate-800/60"
              title={`View ${dare.creator.name || dare.creator.handle}'s Profile`}
            >
              <img
                src={dare.creator.avatar}
                alt={dare.creator.name}
                className="h-5 w-5 rounded-full object-cover ring-1 ring-slate-700 group-hover/creator:ring-indigo-400 group-hover/creator:scale-110 transition-transform shrink-0"
              />
              <span className="font-mono text-[11px] text-slate-300 truncate">
                by <span className="text-white font-semibold group-hover/creator:text-indigo-400 group-hover/creator:underline">{dare.creator.handle}</span>
              </span>
            </button>

            {dare.acceptedBy ? (
              <button
                id={`card-challenger-profile-${dare.id}`}
                onClick={(e) => {
                  e.stopPropagation();
                  playSound('click');
                  onOpenProfile?.(dare.acceptedBy!.id || dare.acceptedBy!.handle);
                }}
                className="flex items-center gap-1 font-mono text-[10px] text-cyan-400 bg-cyan-950/30 px-2 py-0.5 rounded border border-cyan-500/20 hover:border-cyan-400/60 hover:bg-cyan-900/40 transition-all shrink-0 max-w-[130px] truncate cursor-pointer active:scale-95"
                title={`View @${dare.acceptedBy.handle}'s Profile`}
              >
                <UserCheck className="h-3 w-3 shrink-0" />
                <span className="truncate">@{dare.acceptedBy.handle}</span>
              </button>
            ) : currentUser.streak && currentUser.streak > 0 ? (
              <div className="flex items-center gap-1 bg-amber-950/20 text-amber-400 border border-amber-500/30 px-1.5 py-0.5 rounded text-[10px] font-bold font-mono shrink-0">
                <Flame className="h-3 w-3" />
                <span>{currentUser.streak} streak</span>
              </div>
            ) : null}
          </div>

          {/* Action Row */}
          <div className="flex items-center gap-1.5 min-w-0">
            {/* Primary Action Button */}
            {dare.status === 'open' && (
              <button
                id={`accept-dare-btn-${dare.id}`}
                onClick={() => {
                  playSound('accept');
                  onAccept(dare);
                }}
                className="flex-1 min-w-0 flex items-center justify-center gap-1.5 rounded-xl bg-gradient-to-r from-cyan-500 to-teal-400 h-9 px-3 text-xs font-bold text-slate-950 hover:from-cyan-400 hover:to-teal-300 transition-all glow-cyan active:scale-95 truncate cursor-pointer shadow-md"
              >
                <Flame className="h-3.5 w-3.5 shrink-0" />
                <span className="font-tech tracking-wider uppercase truncate">Accept Challenge</span>
              </button>
            )}

            {dare.status === 'accepted' && isAcceptedByMe && (
              <button
                id={`submit-proof-btn-${dare.id}`}
                onClick={() => {
                  playSound('laser');
                  onSubmitProof(dare);
                }}
                className="flex-1 min-w-0 flex items-center justify-center gap-1.5 rounded-xl bg-gradient-to-r from-pink-500 to-rose-500 h-9 px-3 text-xs font-bold text-white hover:from-pink-400 hover:to-rose-400 transition-all glow-magenta active:scale-95 truncate cursor-pointer shadow-md"
              >
                <Sparkles className="h-3.5 w-3.5 shrink-0" />
                <span className="font-tech tracking-wider uppercase truncate">Submit Proof</span>
              </button>
            )}

            {dare.status === 'accepted' && !isAcceptedByMe && (
              <div className="flex-1 min-w-0 flex items-center justify-center gap-1 rounded-xl border border-amber-500/30 bg-amber-950/20 h-9 px-2 text-[11px] font-mono text-amber-300 truncate">
                <Clock className="h-3 w-3 animate-spin shrink-0" />
                <span className="truncate">In Progress</span>
              </div>
            )}

            {dare.status === 'submitted' && (
              <button
                id={`view-proof-details-btn-${dare.id}`}
                onClick={() => {
                  playSound('click');
                  onViewProof(dare);
                }}
                className="flex-1 min-w-0 flex items-center justify-center gap-1.5 rounded-xl border border-purple-500/50 bg-purple-950/40 h-9 px-3 text-xs font-bold text-purple-200 hover:bg-purple-900/50 transition-all glow-purple active:scale-95 truncate cursor-pointer"
              >
                <Hourglass className="h-3.5 w-3.5 text-purple-300 animate-spin shrink-0" />
                <span className="font-tech tracking-wider uppercase truncate">Vote Verdict</span>
              </button>
            )}

            {dare.status === 'verified' && (
              <button
                id={`view-proof-details-btn-${dare.id}`}
                onClick={() => {
                  playSound('click');
                  onViewProof(dare);
                }}
                className="flex-1 min-w-0 flex items-center justify-center gap-1.5 rounded-xl border border-emerald-500/40 bg-emerald-950/30 h-9 px-3 text-xs font-bold text-emerald-300 hover:bg-emerald-900/40 transition-all glow-green active:scale-95 truncate cursor-pointer"
              >
                <CheckCircle2 className="h-3.5 w-3.5 text-emerald-400 shrink-0" />
                <span className="font-tech tracking-wider uppercase truncate">Completed</span>
              </button>
            )}

            {/* Social Micro-Interactions */}
            <div className="flex items-center gap-1 shrink-0">
              {/* High-Roller Stake Button */}
              {onOpenStake && (dare.status === 'open' || dare.status === 'accepted') && (
                <button
                  id={`stake-dare-btn-${dare.id}`}
                  onClick={() => {
                    playSound('purchase');
                    onOpenStake(dare);
                  }}
                  title="Wager Cred on Dare Execution (1.5x Multiplier)"
                  className="flex h-9 items-center gap-1 rounded-xl border border-amber-500/40 bg-amber-500/10 px-2.5 text-xs text-amber-300 hover:border-amber-400 hover:bg-amber-500/20 transition-all shrink-0 cursor-pointer shadow-sm font-bold"
                >
                  <Flame className="h-3.5 w-3.5 text-amber-400 animate-pulse" />
                  <span className="hidden sm:inline text-[11px]">Stake</span>
                </button>
              )}

              {/* Like Button */}
              <button
                id={`like-dare-btn-${dare.id}`}
                onClick={() => {
                  playSound('click');
                  onToggleLike(dare.id);
                }}
                title={isLiked ? 'Unlike' : 'Give Voltage (Like)'}
                className={`flex h-9 items-center gap-1 rounded-xl border px-2 text-xs transition-colors shrink-0 cursor-pointer ${
                  isLiked
                    ? 'border-pink-500/50 bg-pink-950/40 text-pink-400'
                    : 'border-slate-800 bg-slate-900/60 text-slate-400 hover:border-slate-700 hover:text-slate-200'
                }`}
              >
                <Heart className={`h-3.5 w-3.5 ${isLiked ? 'fill-pink-500 text-pink-500' : ''}`} />
                <span className="font-mono text-[11px]">{dare.likes}</span>
              </button>

              {/* Comments Button */}
              <button
                id={`comments-dare-btn-${dare.id}`}
                onClick={() => {
                  playSound('click');
                  onToggleComments(dare);
                }}
                title="Transmissions & Comments"
                className="flex h-9 items-center gap-1 rounded-xl border border-slate-800 bg-slate-900/60 px-2 text-xs text-slate-400 hover:border-cyan-500/40 hover:text-cyan-300 transition-colors shrink-0 cursor-pointer"
              >
                <MessageSquare className="h-3.5 w-3.5" />
                <span className="font-mono text-[11px]">{dare.comments.length}</span>
              </button>

              {/* Share & Copy Unified Button with In-Place Feedback */}
              <div className="relative shrink-0">
                {copied && (
                  <div
                    id={`link-copied-tooltip-${dare.id}`}
                    role="tooltip"
                    className="absolute -top-7 right-0 z-30 flex items-center gap-1 rounded border border-emerald-500/60 bg-[#071318] px-1.5 py-0.5 text-[9px] font-mono font-bold text-emerald-300 shadow-xl glow-green whitespace-nowrap"
                  >
                    <Check className="h-2.5 w-2.5 text-emerald-400" />
                    <span>Copied!</span>
                  </div>
                )}
                <button
                  id={`share-dare-btn-${dare.id}`}
                  type="button"
                  onClick={handleNativeShare}
                  title="Share / Copy Link"
                  className={`flex h-9 items-center justify-center gap-1 rounded-xl border px-2 text-xs transition-all shrink-0 cursor-pointer ${
                    copied
                      ? 'border-emerald-500/60 bg-emerald-950/60 text-emerald-300'
                      : 'border-slate-800 bg-slate-900/60 text-slate-400 hover:border-indigo-500/40 hover:text-indigo-300'
                  }`}
                >
                  {copied ? (
                    <Check className="h-3.5 w-3.5 text-emerald-400" />
                  ) : (
                    <Share2 className="h-3.5 w-3.5" />
                  )}
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
